[build]
target = "thumbv7em-none-eabihf" 

[target.thumbv7em-none-eabihf]
runner = "qemu-system-arm -cpu cortex-m4 -machine netduinoplus2 -display none -semihosting-config enable=on,target=native -kernel"

rustflags = [
  "-C", "link-arg=-Tqemu-link.ld"
]