name: Deploy Rust Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Add target
        run: rustup target add thumbv7em-none-eabihf

      - name: Build documentation
        run: cargo +nightly doc --no-deps --target-dir Documentation
     
      - name: Generate index.html file
        run: |
            echo "<meta http-equiv=refresh content=0;url=wasm_oidc_plugin/index.html>" > target/doc/index.html
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v1
        with:
            path: ./target/doc

  deploy:
        needs: build
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.pages.outputs.page_url }}

        steps:
          - name: Deploy documentation
            id: pages
            uses: actions/deploy-pages@v2
