name: Deploy Rust Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.pages.outputs.page_url }}

        steps:
          - name: Deploy documentation
            id: pages
            uses: actions/deploy-pages@v2
